### ISSUE TITLE
Alternative RC cars

### ISSUE THREAD

**Issue by subodh-malgonde** [mit-racecar/hardware#6]
Hi,

I am going to build a car based on the MIT racecar platform. I am constrained on budget, so I am trying to evaluate if I can cut down on the cost of the base platform. Hoping to get some help here.

Are there reasons why this repo recommends the Traxxas model? I was looking for cheaper alternative RC cars which also have: 

- Brushless DC motor
- 1/10 scale
- ESC
- 4WD

Is 4WD drive required? What could go wrong If I choose a 2WD? Also, if I use a brushed DC motor instead of a brushless DC motor, will control via VESC be an issue?

Are there other things one should keep in mind before purchasing the car?

**Comment by mboulet** [comment]
Excellent, I'm happy to hear of your interest. Sorry for the delay getting back to you. The Traxxas car has mounting holes that line up with the plate design. Otherwise you can choose another vehicle base and make a custom set of plates. 4wd is not required, although I've not tried with 2wd. I've never tried the VESC with a brushed motor so I would suggest reading the VESC site and docs first (I suspect that it works). You will want to choose a vehicle that is large enough to carry the computer, sensors, and electronics. I would suggest finding a vehicle with a conventional pwm servo motor for steering. Some of the cheapest RC cars have steering motors that do not allow fine control. Good luck!
